// Mocks generated by Mockito 5.4.6 from annotations
// in greenleaf/test/Cart/Unit/UseCase/cart_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:greenleaf/Features/Cart/Domain/Entity/cart_product.dart' as _i4;
import 'package:greenleaf/Features/Cart/Domain/Repository/cart_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepo extends _i1.Mock implements _i2.CartRepo {
  MockCartRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CartProduct>> getCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, []),
            returnValue: _i3.Future<List<_i4.CartProduct>>.value(
              <_i4.CartProduct>[],
            ),
          )
          as _i3.Future<List<_i4.CartProduct>>);

  @override
  _i3.Future<void> addToCart({required _i4.CartProduct? entity}) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [], {#entity: entity}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromCart({required String? plantId}) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [], {#plantId: plantId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
