// Mocks generated by Mockito 5.4.6 from annotations
// in greenleaf/test/Cart/Unit/Repo/repo_unit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:greenleaf/Features/Cart/Data/Models/cart_product_model.dart'
    as _i4;
import 'package:greenleaf/Features/Cart/Data/Source/Local/cart_local_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartLocalSource extends _i1.Mock implements _i2.CartLocalSource {
  MockCartLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> removeFromCart(String? plantId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [plantId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveCartList(List<_i4.CartProductModel>? plants) =>
      (super.noSuchMethod(
            Invocation.method(#saveCartList, [plants]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addToCart(_i4.CartProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [product]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CartProductModel>> getCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, []),
            returnValue: _i3.Future<List<_i4.CartProductModel>>.value(
              <_i4.CartProductModel>[],
            ),
          )
          as _i3.Future<List<_i4.CartProductModel>>);

  @override
  _i3.Future<void> decreaseCartItem(String? plantId) =>
      (super.noSuchMethod(
            Invocation.method(#decreaseCartItem, [plantId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
